# Site settings
title: David East
email: david@firebase.com
description: "All things front-end. Heavy on the Firebase & JavaScript."
baseurl: ""
url: "http://davideast.firebaseapp.com"

# Build settings
markdown: kramdown
kramdown:
    input: GFM

permalink: pretty
exclude: ['node_modules', 'LICENSE', 'README.md', 'gulpfile.js', 'package.json']
